import io
import os
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from backend.database.connection import supabase
from backend.utils.security import get_current_user
import openpyxl
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

router = APIRouter(prefix="/api/reports", tags=["reports"])

@router.get("/excel")
def export_excel(current_user = Depends(get_current_user)):
    """Generates an Excel spreadsheet containing all active predictions/cases."""
    try:
        res = supabase.table("predictions").select("*").order("created_at", desc=True).execute()
        records = res.data or []
        
        # Create Workbook
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "FraudGuard Investigations"
        
        headers = [
            "Case ID", "Beneficiary ID", "Name", "Phone", "State", "Scheme", 
            "Claims/Month", "Amount (INR)", "Location Cluster", "Account Age (days)", 
            "Risk Score (%)", "Severity", "Status", "Assigned Officer", "Notes", "Created At"
        ]
        ws.append(headers)
        
        for r in records:
            ws.append([
                r.get("id"),
                r.get("beneficiary_id"),
                r.get("name"),
                r.get("phone"),
                r.get("state"),
                r.get("scheme"),
                r.get("claims_per_month"),
                r.get("amount"),
                r.get("location_cluster"),
                r.get("account_age_days"),
                r.get("risk_score"),
                r.get("severity"),
                r.get("status"),
                r.get("assigned_to"),
                r.get("officer_notes"),
                r.get("created_at")
            ])
            
        # Save to local reports folder
        reports_excel_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports", "excel")
        os.makedirs(reports_excel_dir, exist_ok=True)
        local_path = os.path.join(reports_excel_dir, "fraudguard_cases.xlsx")
        wb.save(local_path)

        # Save to buffer for streaming
        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        
        return StreamingResponse(
            buffer, 
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": "attachment; filename=fraudguard_cases.xlsx"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to export Excel report: {str(e)}")

@router.get("/pdf")
def export_pdf(current_user = Depends(get_current_user)):
    """Generates a PDF Investigation Report detailing fraud classifications and telemetry metrics."""
    try:
        res = supabase.table("predictions").select("*").order("risk_score", desc=True).execute()
        records = res.data or []
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=54, bottomMargin=54)
        story = []
        
        styles = getSampleStyleSheet()
        
        # Define Custom Styles for dark/crimson security theme
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            textColor=colors.HexColor('#cc0000'),
            spaceAfter=6,
            alignment=1
        )
        subtitle_style = ParagraphStyle(
            'SubtitleStyle',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            textColor=colors.HexColor('#666666'),
            spaceAfter=20,
            alignment=1
        )
        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=12,
            textColor=colors.HexColor('#1a1a1a'),
            spaceBefore=12,
            spaceAfter=8
        )
        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12
        )
        
        # Header
        story.append(Paragraph("🛡️ FRAUDGUARD WAR ROOM INTELLIGENCE REPORT", title_style))
        story.append(Paragraph(f"CONFIDENTIAL // GENERATED BY {current_user.email.upper()}", subtitle_style))
        story.append(Spacer(1, 10))
        
        # Summary paragraph
        total_cases = len(records)
        escalated = sum(1 for r in records if r.get("status") == "ESCALATED")
        resolved = sum(1 for r in records if r.get("status") == "RESOLVED")
        open_cases = total_cases - escalated - resolved
        
        story.append(Paragraph("Executive Summary", h2_style))
        summary_text = (
            f"This dossier contains details of {total_cases} flagged anomalies analyzed under active "
            f"GPU-accelerated models. Case files show {escalated} escalated investigations, {resolved} resolved issues, "
            f"and {open_cases} currently open cases pending officer assignments."
        )
        story.append(Paragraph(summary_text, body_style))
        
        # Table of top flagged cases
        story.append(Paragraph("Top Critical Fraud Cases", h2_style))
        
        table_data = [["Case ID", "Beneficiary", "Scheme", "State", "Amount (INR)", "Risk Score", "Severity"]]
        
        # Take top 15 most critical cases
        critical_cases = [r for r in records if r.get("risk_score", 0) >= 50][:15]
        for c in critical_cases:
            table_data.append([
                c.get("id"),
                c.get("name")[:15],
                c.get("scheme"),
                c.get("state"),
                f"Rs. {float(c.get('amount')):,.2f}",
                f"{int(c.get('risk_score'))}%",
                c.get("severity")
            ])
            
        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0d0202')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#cc0000')),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 9),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#fcfcfc')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#eeeeee')),
            ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,1), (-1,-1), 8),
            ('TOPPADDING', (0,1), (-1,-1), 4),
            ('BOTTOMPADDING', (0,1), (-1,-1), 4),
        ]))
        
        story.append(t)
        
        # Build Document
        doc.build(story)
        pdf_data = buffer.getvalue()
        
        # Save to local reports folder
        reports_pdf_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports", "pdf")
        os.makedirs(reports_pdf_dir, exist_ok=True)
        local_path = os.path.join(reports_pdf_dir, "fraudguard_dossier.pdf")
        with open(local_path, "wb") as f:
            f.write(pdf_data)
            
        buffer.seek(0)
        
        return StreamingResponse(
            buffer, 
            media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=fraudguard_dossier.pdf"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to export PDF report: {str(e)}")
